name: simple-workflow

on: 
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Premier message
        run: echo "Récupération du code source"
        
      - name: Checkout 
        uses: actions/checkout@v4.2.2 

      - name: Deuxieme message 
        run: echo "Vérification terminée"
